baseURL = 'https://zivotvusa.cz/'
languageCode = 'cs'
title = 'Život v USA - Americké zkušenosti očima Čecha'
theme = 'PaperMod'

[pagination]
  pagerSize = 5

[params]
  title = 'Život v USA - Americké zkušenosti očima Čecha'
  description = 'Osobní blog o životě v USA očima českého expata. Finanční srovnání, práce, bydlení a každodenní život v Americe vs Česko. Dlouhodobé zkušenosti z první ruky.'
  keywords = ['život v usa', 'český expat', 'amerika vs česko', 'práce v usa', 'finance usa']
  author = 'Bohumil Lánský'

  # Zobrazování článků (Regular Mode je výchozí)
  ShowReadingTime = true
  ShowShareButtons = true
  ShareButtons = ["facebook", "twitter", "linkedin"]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = false
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  
  disableSpecial1stPost = true

[params.homeInfoParams]
  Content = """
  Bude to 7 let, co jsme se s rodinou přestěhovali z Česka do Spojených států. Na blogu zivotvusa.cz sdílím
  osobní zkušenosti s životem v USA – co nás překvapilo, co nám chybí z domova a co nás naopak nadchlo.

  Porovnávám každodenní život, peníze, zvyky i mentalitu – bez přikrášlování, ale s nadhledem.
  Chci ukázat, co může být v USA inspirací, a zároveň připomenout, co je v Česku často lepší, než si sami uvědomujeme.
  """

# Social Icons - only the ones you want enabled
[[params.socialIcons]]
  name = "facebook"
  url = "https://facebook.com/yourusername"
[[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/yourusername"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/yourusername"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/yourusername"

[params.label]
  text = "Život v USA"

# Výstupy pro vyhledávání
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Vyhledávání
[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4

# Menu
[[menu.main]]   
  name = "Blog"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Kategorie"
  url = "/categories/"
  weight = 20

[[menu.main]]
  name = "Tagy"
  url = "/tags/"
  weight = 30

[[menu.main]]
  name = "Hledat"
  url = "/search/"
  weight = 40